# Site settings
baseurl = "https://mystictot.me/"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Shyam Saini"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXX-Y"

[params]

        # Images settings
        # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
        # You may place your images in corresponding folders and then set only filenames below to
        # change page's appearance

        favicon = "favicon.ico"
        appletouchicon = "apple-touch-icon-precomposed.png"
        background = "bg1.jpg"
        avatar = "shyam.jpg"

        # Personal settings

    name = "Shyam Saini - MysticTot"
        position = "Kernel Dev blah blah"
	email = "mayhs11saini@gmail.com"
	[params.contact]
		enable = false
		formTitle = "Touch Me!"
		namePlaceholder = "Name"
		emailPlaceholder = "Email"
		messagePlaceholder = "Message"
		buttonText = "Send it"
	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "https://twitter.com/mystictot"

	[[params.social]]
		title = "Github"
		icon = "fa-github"
		link = "https://github.com/mystictot"
			
	# Footer settings
	[params.footer]
		copyright = "Shyam Saini"
		
